### ISSUE TITLE
Installing gbea fails

### ISSUE THREAD

**Issue by CIGbalance** [ttusar/coco#41]
Downloading the appropriate files for the rw-problems seems to fail for me:

```
root@0518b472f5ad:/coco# python do.py test-toy-socket
MAKE	clean in code-experiments/rw-problems
CHDIR	/coco/code-experiments/rw-problems
COPY	Makefile.in -> Makefile
rm -f socket_server

MAKE	all in code-experiments/rw-problems
CHDIR	/coco/code-experiments/rw-problems
COPY	Makefile.in -> Makefile
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion socket_server.c -o socket_server '-Wl,-rpath,$ORIGIN' 

/bin/sh: 1: ./code-experiments/rw-problems/socket_server: Permission denied
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
Traceback (most recent call last):
  File "do.py", line 1310, in <module>
    main(sys.argv[1:])
  File "do.py", line 1304, in main
    elif cmd == 'test-toy-socket': test_toy_socket(port=port, package_install_option=package_install_option)
  File "do.py", line 981, in test_toy_socket
    build_python(package_install_option=package_install_option)
  File "do.py", line 318, in build_python
    _prep_python()
  File "do.py", line 300, in _prep_python
    RELEASE, {"COCO_VERSION": git_version(pep440=True)})
  File "/coco/code-experiments/tools/amalgamate.py", line 62, in amalgamate
    amalgator.process_file(filename)
  File "/coco/code-experiments/tools/amalgamate.py", line 49, in process_file
    self.process_file(include_file)
  File "/coco/code-experiments/tools/amalgamate.py", line 49, in process_file
    self.process_file(include_file)
  File "/coco/code-experiments/tools/amalgamate.py", line 49, in process_file
    self.process_file(include_file)
  File "/coco/code-experiments/tools/amalgamate.py", line 38, in process_file
    with open(filename) as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'code-experiments/src/rw_top_trumps.h'

```

**Comment by ttusar** [comment]
I did some changes, please try again

**Comment by CIGbalance** [comment]
@ttusar  I did, the error above has been fixed. I also fixed the permission issue by using `bash` instead of `sh`. However, I still can't execute the socket_server binary file.
```
$ bash socket_server
socket_server: socket_server: cannot execute binary file
```
What type of file is that? Should I be able to execute it like that?

**Comment by ttusar** [comment]
This should start the server on port 1212 
````
./socket_server 1212
````
However, you don't need to invoke it like this, you can do 
````
python do.py verbose run-socket-servers
````
and both socket servers (C and Python) should start.

**Comment by CIGbalance** [comment]
Unfortunately, this does not work for me.
`./socket_server 1212` gives a permission denied because I am on an ntfs drive. However, I should be able to execute with `bash socket_server 1212`. Then I get the error above. What type of file is it? Is it really a binary or should it be a shell script?

The python script just calls the binary, so it results in the same error.

**Comment by ttusar** [comment]
See slack :-)

**Comment by ttusar** [comment]
Closing this issue and opening a new one for the current problem with Linux
