### ISSUE TITLE
Error about "output not formatted as expected"

### ISSUE THREAD

**Issue by ttusar** [ttusar/coco#42]
After previously invoking `python do.py verbose run-socket-servers`, I get the following error when calling `python do.py verbose run-c`

````
Blip:ttusar-coco tea$ python do.py verbose run-c
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/c/coco.c
EXPAND	code-experiments/build/c/coco.c.in to code-experiments/build/c/coco.c
EXPAND	code-experiments/src/coco.h to code-experiments/build/c/coco.h
COPY	code-experiments/build/c/coco.c -> code-experiments/examples/bbob2009-c-cmaes/coco.c
EXPAND	code-experiments/build/c/coco.h to code-experiments/examples/bbob2009-c-cmaes/coco.h
WRITE	code-experiments/build/c/REVISION
WRITE	code-experiments/build/c/VERSION
MAKE	clean in code-experiments/build/c
CHDIR	/Users/tea/Delo/Github/ttusar-coco/code-experiments/build/c
COPY	Makefile.in -> Makefile
rm -f coco.o 
rm -f example_experiment.o example_experiment 

MAKE	all in code-experiments/build/c
CHDIR	/Users/tea/Delo/Github/ttusar-coco/code-experiments/build/c
COPY	Makefile.in -> Makefile
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment.o example_experiment.c
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o coco.o coco.c
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment coco.o example_experiment.o -lm '-Wl,-rpath,$ORIGIN' -L.  

RUN	./example_experiment in code-experiments/build/c
Error within message evaluation: MarioGAN.jar output not formatted as expected, got 0.08797774658203125  
Message = s rw-mario-gan t objectives r 1 f 13 i 1 d 10 x 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 
Error: MarioGAN.jar output not formatted as expected, got 0.08797774658203125 
Closing socket
Traceback (most recent call last):
  File "code-experiments/rw-problems/socket_server.py", line 174, in <module>
ERROR: return value=1
Running the example experiment... (might take time, be patient)
COCO INFO: Results will be output to folder exdata/RS_on_mario-gan-011

COCO INFO: 26.01.20 02:36:06, d=10, running: f10.f11.f12.f13.COCO FATAL ERROR: socket_communication_save_response(): Incorrect response 1.1397999999999999e+00   (size 0)

    socket_server_start(port=port, silent=silent)
  File "code-experiments/rw-problems/socket_server.py", line 153, in socket_server_start
    raise e
  File "code-experiments/rw-problems/socket_server.py", line 146, in socket_server_start
    response = evaluate_message(message)
  File "code-experiments/rw-problems/socket_server.py", line 100, in evaluate_message
    raise e
  File "code-experiments/rw-problems/socket_server.py", line 82, in evaluate_message
    values = evaluate_objectives(suite_name, func, instance, x)
  File "/Users/tea/Delo/Github/ttusar-coco/code-experiments/rw-problems/mario_gan/mario_gan_evaluator.py", line 359, in evaluate_mario_gan
    out[i] = fun(x, netG, d)
  File "/Users/tea/Delo/Github/ttusar-coco/code-experiments/rw-problems/mario_gan/mario_gan_evaluator.py", line 275, in basicFitnessSimAStar
    return executeSimulation(x, netG, dim, 1, 0)
  File "/Users/tea/Delo/Github/ttusar-coco/code-experiments/rw-problems/mario_gan/mario_gan_evaluator.py", line 124, in executeSimulation
    raise ValueError('MarioGAN.jar output not formatted as expected, got {} '.format(result))
ValueError: MarioGAN.jar output not formatted as expected, got 0.08797774658203125 
Blip:ttusar-coco tea$ 
````

**Comment by ttusar** [comment]
@TheHedgeify can you have a look?

**Comment by CIGbalance** [comment]
Yes, I think this has to do with the different states our repositories are in, so hopefully this would be fixed by a pull request. However, I can't test it because I don't have a working version of GBEA. Will look into this as soon as I can run the socket server stuff.

**Comment by ttusar** [comment]
I think this issue can be closed

**Comment by ttusar** [comment]
This issue reappears when I do: 
```
python do.py verbose run-rw-experiment suite=rw-mario-gan observer=bbob budget_multiplier=2 suite_options="instance_indices: 1 function_indices: 1,14"
```
It works for function 1, but fails for function 14 with the following error:
```
PYTHON  rw_example_experiment.py suite=rw-mario-gan observer=bbob budget_multiplier=2 suite_options=instance_indices: 1 function_indices: 1,14 in code-experiments\build\python
Socket server (Python) reset
  ror within message evaluation: MarioGAN.jar output not formatted as expected, got 1.2288
Message = s rw-mario-gan t objectives r 1 f 14 i 1 d 10 x -9.26004480e-01 -6.93789800e-01 -3.24020553e-02 8.59968639e-01 -1.77871393e-01 -3.04542773e-01 7.67442852e-01 7.67555832e-01 -2.85809961e-01 -8.76870865e-01
 ocket server (Python) error: MarioGAN.jar output not formatted as expected, got 1.2288
Traceback (most recent call last):
  File "code-experiments\rw-problems\socket_server.py", line 170, in <module>
    socket_server_start(port=port, silent=silent)
  File "code-experiments\rw-problems\socket_server.py", line 150, in socket_server_start
    raise e
  File "code-experiments\rw-problems\socket_server.py", line 140, in socket_server_start
    ERROR: return value=1
```
I get the same problem for different input values (tried on different computers). It fails on Windows and on Linux (haven't tried Mac yet).

**Comment by ttusar** [comment]
Recently fixed thanks to @TheHedgeify
