### ISSUE TITLE
Running Socket servers fails

### ISSUE THREAD

**Issue by CIGbalance** [ttusar/coco#45]
What I tried to do:  Install, and then `python do.py run-socket-servers`
I ran into an issue with a missing `Makefile.in` for top-trumps. But there was a `Makefile` so I just copied the contents from that file into `Makefile.in`.

However, the file `utils/hoy.cpp` does not exist?

```
root@1cd6b0627591:/gbea# python do.py run-socket-servers
MAKE	clean in code-experiments/rw-problems/top_trumps
CHDIR	/gbea/code-experiments/rw-problems/top_trumps
COPY	Makefile.in -> Makefile
Traceback (most recent call last):
  File "do.py", line 1314, in <module>
    main(sys.argv[1:])
  File "do.py", line 1306, in main
    elif cmd == 'run-socket-servers': run_socket_servers(force_download=force_rw_download)
  File "do.py", line 946, in run_socket_servers
    build_socket_servers(force_download=force_download)
  File "do.py", line 916, in build_socket_servers
    build_rw_top_trumps_server(force_download=force_download, exclusive_evaluator=False)
  File "do.py", line 886, in build_rw_top_trumps_server
    _build_rw_top_trumps_lib()
  File "do.py", line 853, in _build_rw_top_trumps_lib
    verbose=_build_verbosity)
  File "/gbea/code-experiments/tools/cocoutils.py", line 211, in make
    copy_file('Makefile.in', 'Makefile')
  File "/gbea/code-experiments/tools/cocoutils.py", line 183, in copy_file
    copyfile(source, destination)
  File "/usr/local/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'Makefile.in'
root@1cd6b0627591:/gbea# python do.py run-socket-servers
MAKE	clean in code-experiments/rw-problems/top_trumps
CHDIR	/gbea/code-experiments/rw-problems/top_trumps
COPY	Makefile.in -> Makefile
ERROR: return value=2
make: *** No rule to make target 'utils/hoy.cpp', needed by '.depend'.  Stop.
```

**Comment by ttusar** [comment]
I think I know what the problem is... Please remove the `top_trumps` folder (or, a safer version is to rename it to something else), then retry `python do.py run-socket-servers`. 

This will trigger downloading of the "new" `top_trumps` folder and it should be fine then. If you encounter any problems, let me know.

**Comment by ttusar** [comment]
Oh, and do the same (remove or rename) the `mario_gan` folder too.

**Comment by CIGbalance** [comment]
Yes, that solved it, thanks :)
