### ISSUE TITLE
time.clock deprecated in Python 3.8

### ISSUE THREAD

**Issue by lbliek** [ttusar/coco#48]
In step 3 of **Getting Started** I get the following error when using Python 3.8 because time.clock has been deprecated:

Benchmarking solver '<function random_search' with budget=2*dimension on b'bbob' suite, Wed Jul 29 22:12:38 2020
Traceback (most recent call last):
  File "example_experiment.py", line 281, in <module>
    main(budget, max_runs, current_batch, number_of_batches)
  File "example_experiment.py", line 247, in main
    t0 = time.clock()
AttributeError: module 'time' has no attribute 'clock'

**Comment by lbliek** [comment]
Never mind, I used git clone https://github.com/numbbo/coco.git in step 1 so I was in the wrong repository. Maybe change the link in the readme to the ttusar repository just to be sure.
